# Generated by Django 5.2.17 on 2026-09-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0002_learnergrammartopic_introduced_in'),
        ('lessons', '0002_progressreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SlugField(max_length=40)),
                ('source_name', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['-published_at'], name='articles_ar_publish_c1a2fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='articles.article')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_uses', to='learners.learner')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_uses', to='lessons.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'learner'), name='unique_article_per_learner')],
            },
        ),
    ]
