# Generated by Django 5.2.17 on 2026-09-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuse',
            name='rejected',
            field=models.BooleanField(default=False, help_text='She asked for a different one instead of reading it'),
        ),
    ]
