# Generated by Django 5.2.17 on 2026-09-09 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('summary_es', models.TextField(help_text='Contrastive ES -> EN explanation, in Spanish')),
                ('examples', models.JSONField(blank=True, default=list, help_text='[{wrong, right, note_es}]')),
                ('related_subcategories', models.JSONField(blank=True, default=list, help_text='ErrorItem subcategories this topic addresses')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_speaking', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('cefr_listening', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('cefr_reading', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('cefr_writing', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('target_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B2', max_length=2)),
                ('placement_done', models.BooleanField(default=False)),
                ('placement_notes', models.TextField(blank=True)),
                ('goal_statement', models.TextField(blank=True, help_text='e.g. technical interviews, daily standups')),
                ('native_language', models.CharField(default='es', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('seed_vocabulary', models.JSONField(blank=True, default=list, help_text='List of target terms')),
                ('is_active', models.BooleanField(default=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learners.track')),
            ],
            options={
                'ordering': ['track', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearnerGrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('introduced', 'Introduced'), ('practicing', 'Practicing'), ('mastered', 'Mastered')], default='not_started', max_length=12)),
                ('times_targeted', models.PositiveIntegerField(default=0)),
                ('times_avoided', models.PositiveIntegerField(default=0)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_progress', to='learners.learner')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='learners.grammartopic')),
            ],
            options={
                'ordering': ['topic__order'],
                'unique_together': {('learner', 'topic')},
            },
        ),
    ]
