# Generated by Django 5.2.17 on 2026-09-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_question_formation_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_topics', to='learners.learner'),
        ),
        migrations.AddField(
            model_name='topic',
            name='proposed_reason',
            field=models.TextField(blank=True, help_text='Why this was proposed, in Spanish, for her to read'),
        ),
    ]
