# Generated by Django 5.2.17 on 2026-09-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_topic_created_at_topic_learner_topic_proposed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='profile',
            field=models.TextField(blank=True, help_text='About you, for the tutor: job, experience, projects'),
        ),
    ]
