# Generated by Django 5.2.17 on 2026-09-09 22:33

import django.db.models.deletion
import lessons.srs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('speaking', 'Speaking'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('checkpoint', 'Checkpoint')], max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('analyzed', 'Analyzed')], default='planned', max_length=12)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('scheduled_for', models.DateField(db_index=True, default=lessons.srs.today)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_topic', models.ForeignKey(blank=True, help_text='The mini-lesson point of the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learners.grammartopic')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learners.learner')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learners.topic')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='learners.track')),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('report_es', models.TextField(blank=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='learners.learner')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoint', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_es', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('focus_next', models.JSONField(blank=True, default=list)),
                ('fluency_wpm', models.FloatField(blank=True, null=True)),
                ('filler_ratio', models.FloatField(blank=True, null=True)),
                ('new_errors_count', models.PositiveIntegerField(default=0)),
                ('recycled_errors_count', models.PositiveIntegerField(default=0)),
                ('errors_avoided_count', models.PositiveIntegerField(default=0)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tutor', 'Tutor'), ('learner', 'Learner')], max_length=8)),
                ('text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='turns/%Y/%m/')),
                ('audio_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('phase', models.CharField(blank=True, max_length=12)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='lessons.lesson')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ErrorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('fluency', 'Fluency'), ('discourse', 'Discourse')], max_length=16)),
                ('subcategory', models.CharField(choices=[('agreement', 'Agreement'), ('articles', 'Articles'), ('aspect', 'Aspect'), ('circumlocution', 'Circumlocution'), ('collocation', 'Collocation'), ('conditionals', 'Conditionals'), ('connectors', 'Connectors'), ('directness', 'Directness'), ('false_friend', 'False friend'), ('fillers', 'Fillers'), ('l1_interference', 'L1 interference'), ('long_pause', 'Long pause'), ('modals', 'Modals'), ('phoneme', 'Phoneme'), ('plurals', 'Plurals'), ('politeness', 'Politeness'), ('prepositions', 'Prepositions'), ('register', 'Register'), ('self_correction', 'Self correction'), ('sentence_stress', 'Sentence stress'), ('tense', 'Tense'), ('word_order', 'Word order'), ('word_stress', 'Word stress'), ('wrong_word', 'Wrong word')], max_length=20)),
                ('learner_produced', models.TextField(help_text='Exactly what the learner said or wrote')),
                ('correction', models.TextField()),
                ('explanation', models.TextField(help_text='In Spanish, short, contrastive with Spanish')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('srs_box', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateField(default=lessons.srs.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('mastered', 'Mastered'), ('dismissed', 'Dismissed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='learners.learner')),
                ('source_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='lessons.lesson')),
                ('source_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='lessons.turn')),
            ],
            options={
                'ordering': ['-occurrences', 'next_review_at', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=80)),
                ('definition_en', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('target', 'Target'), ('emerging', 'Emerging'), ('acquired', 'Acquired')], default='target', max_length=10)),
                ('srs_box', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateField(default=lessons.srs.today)),
                ('times_produced', models.PositiveIntegerField(default=0, help_text='Spontaneous uses by the learner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to='learners.learner')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab', to='learners.track')),
            ],
            options={
                'ordering': ['next_review_at', 'term'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['learner', '-started_at'], name='lesson_learner_started_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('lesson', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='erroritem',
            index=models.Index(fields=['learner', 'status', 'next_review_at'], name='error_due_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabitem',
            index=models.Index(fields=['learner', 'status', 'next_review_at'], name='vocab_due_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabitem',
            unique_together={('learner', 'term')},
        ),
    ]
