# Generated by Django 5.2.17 on 2026-09-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_learnergrammartopic_introduced_in'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_es', models.TextField()),
                ('improving', models.JSONField(blank=True, default=list)),
                ('stuck', models.JSONField(blank=True, default=list)),
                ('focus', models.JSONField(blank=True, default=list)),
                ('lessons_covered', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learners.learner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
